version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_URL=authenticationDB
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - authenticationVolume:/var/lib/mysql
    networks:
      - authenticationNetwork

  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - authenticationNetwork

  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - "5002:5002"
    networks:
      - authenticationNetwork

  adminer:
    image: adminer
    ports:
      - "8083:8080"
    networks:
      - authenticationNetwork
      - storeNetwork

  storeDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_URL=storeDatabase
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - storeVolume:/var/lib/mysql
    networks:
      - ownerNetwork
      - customerNetwork
      - courierNetwork
      - storeNetwork

  storeDBMigration:
    image: storedbmigration
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
      storeDatabase:
          condition: service_healthy
    networks:
      - storeNetwork

  owner:
    image: owner
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
      - storeDBMigration
    ports:
      - "5005:5005"
    networks:
      - ownerNetwork

  customer:
    image: customer
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
      - storeDBMigration
    ports:
      - "5004:5004"
    networks:
      - customerNetwork

  courier:
    image: courier
    environment:
      - DATABASE_URL=storeDatabase
    depends_on:
      - storeDBMigration
    ports:
      - "5003:5003"
    networks:
      - courierNetwork

  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    networks:
      - customerNetwork
      - courierNetwork
      - ownerNetwork

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077" # mozda i ovo nije potrebno
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - storeNetwork

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # nije bitno za workere, samo za dashboard
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - storeNetwork

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - storeNetwork

  spark:
    image: spark-app
    depends_on: [spark-master, spark-worker-1, spark-worker-2]
    environment:
      - ENABLE_INIT_DAEMON=false

volumes:
  authenticationVolume:
  storeVolume:

networks:
  authenticationNetwork:
  storeNetwork:

  ownerNetwork:
  courierNetwork:
  customerNetwork:
